{% set version = "1.1.7" %}

package:
  name: vcstool
  version: {{ version }}

source:
  # This source is not actually used, but it is a simple way to trigger a new release of the
  # vcstool shim package for every new vcs2l release
  url: https://pypi.org/packages/source/v/vcs2l/vcs2l-${{ version }}.tar.gz
  sha256: 1d86e685f9e01dda271b89df1b2bd42ca5555f5c0dcbef5cc727d443f25738cd

build:
  noarch: generic
  number: 0
  script: 'echo "this is a dummy package that just depends on vcs2l, no package is actually built"'

requirements:
  run:
    - vcstool ==${{ version }}

test:
  commands:
    - vcs --help
    - vcs-branch --help
    - vcs-bzr --help
    - vcs-custom --help
    - vcs-diff --help
    - vcs-export --help
    - vcs-git --help
    - vcs-help --help
    - vcs-hg --help
    - vcs-import --help
    - vcs-log --help
    - vcs-pull --help
    - vcs-push --help
    - vcs-remotes --help
    - vcs-status --help
    - vcs-svn --help
    - vcs-validate --help

about:
  home: https://github.com/dirk-thomas/vcstool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    vcstool provides a command line tool to invoke vcs commands on multiple repositories.

extra:
  recipe-maintainers:
    - traversaro
    - seanyen
    - wolfv
