{% set name = "vcstool" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dirk-thomas/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 6363747d1ae17747ddb8a0ee448e344439adbfed968fa8bebc1acac817ea162a

build:
  noarch: python
  number: 0
  entry_points:
    - vcs = vcstool.commands.vcs:main
    - vcs-branch = vcstool.commands.branch:main
    - vcs-bzr = vcstool.commands.custom:bzr_main
    - vcs-custom = vcstool.commands.custom:main
    - vcs-diff = vcstool.commands.diff:main
    - vcs-export = vcstool.commands.export:main
    - vcs-git = vcstool.commands.custom:git_main
    - vcs-help = vcstool.commands.help:main
    - vcs-hg = vcstool.commands.custom:hg_main
    - vcs-import = vcstool.commands.import_:main
    - vcs-log = vcstool.commands.log:main
    - vcs-pull = vcstool.commands.pull:main
    - vcs-push = vcstool.commands.push:main
    - vcs-remotes = vcstool.commands.remotes:main
    - vcs-status = vcstool.commands.status:main
    - vcs-svn = vcstool.commands.custom:svn_main
    - vcs-validate = vcstool.commands.validate:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools
    - pyyaml

test:
  imports:
    - vcstool
    - vcstool.clients
    - vcstool.commands
    - vcstool.compat
  commands:
    - vcs --help
    - vcs-branch --help
    - vcs-bzr --help
    - vcs-custom --help
    - vcs-diff --help
    - vcs-export --help
    - vcs-git --help
    - vcs-help --help
    - vcs-hg --help
    - vcs-import --help
    - vcs-log --help
    - vcs-pull --help
    - vcs-push --help
    - vcs-remotes --help
    - vcs-status --help
    - vcs-svn --help
    - vcs-validate --help

about:
  home: https://github.com/dirk-thomas/vcstool
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    vcstool provides a command line tool to invoke vcs commands on multiple repositories.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
